routes/web.php
<?php

Route::redirect('/', '/register');
Route::get('/home', function () {
    $routeName = 'admin.home'; 
    if (session('status')) {
        return redirect()->route($routeName)->with('status', session('status'));
    }

    return redirect()->route($routeName);
});

Auth::routes(['register' => true]);
// Admin

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Jadwal Kuliah
    Route::delete('jadwal-kuliah/destroy', 'JadwalKuliahController@massDestroy')->name('jadwal-kuliah.massDestroy');
    Route::resource('jadwal-kuliah', 'JadwalKuliahController');

    // Mata Kuliah
    Route::delete('mata-kuliah/destroy', 'MataKuliahController@massDestroy')->name('mata-kuliah.massDestroy');
    Route::resource('mata-kuliah', 'MataKuliahController');

    // Time Interval
    Route::delete('time-interval/destroy', 'TimeIntervalControllerr@massDestroy')->name('time-interval.massDestroy');
    Route::resource('time-interval', 'TimeIntervalController');
    
    Route::get('calendar', 'CalendarController@index')->name('calendar.index');
});

app/JadwalKuliah.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class JadwalKuliah extends Model
{
    use SoftDeletes;

    public $table = 'jadwal_kuliah';

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'hari',
        'kelas',
        'mata_kuliah_id',
        'start_time',
        'end_time',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    const HARI = [
        '1' => 'Senin',
        '2' => 'Selasa',
        '3' => 'Rabu',
        '4' => 'Kamis',
        '5' => 'Jumat',
        '6' => 'Sabtu',
        '7' => 'Minggu',
    ];

    public function getDifferenceAttribute()
    {
        return Carbon::parse($this->end_time)->diffInMinutes($this->start_time);
    }

    public function getStartTimeAttribute($value)
    {
        return $value ? Carbon::createFromFormat('H:i:s', $value)->format(config('panel.lesson_time_format')) : null;
    }

    public function setStartTimeAttribute($value)
    {
        $this->attributes['start_time'] = $value ? Carbon::createFromFormat(config('panel.lesson_time_format'),
            $value)->format('H:i:s') : null;
    }

    public function getEndTimeAttribute($value)
    {
        return $value ? Carbon::createFromFormat('H:i:s', $value)->format(config('panel.lesson_time_format')) : null;
    }

    public function setEndTimeAttribute($value)
    {
        $this->attributes['end_time'] = $value ? Carbon::createFromFormat(config('panel.lesson_time_format'),
            $value)->format('H:i:s') : null;
    }

    function mataKuliah()
    {
        return $this->belongsTo(MataKuliah::class, 'mata_kuliah_id');
    }

    public static function isTimeAvailable($hari, $startTime, $endTime, $jadwal)
    {
        $jadwalKuliah = self::where('hari', $hari)
            ->when($jadwal, function ($query) use ($jadwal) {
                $query->where('id', '!=', $jadwal);
            })
            ->where([
                ['start_time', '<', $endTime],
                ['end_time', '>', $startTime],
            ])
            ->count();

        return !$jadwalKuliah;
    }

    public function scopeCalendarByMataKuliahId($query)
    {
        return $query->when(request()->input('mata_kuliah_id'), function ($query) {
                $query->where('mata_kuliah_id', request()->input('mata_kuliah_id'));
            });
    }
}

app/Http/Controllers/Admin/JadwalKuliahController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroyMataKuliahRequest;
use App\Http\Requests\StoreJadwalKuliahRequest;
use App\Http\Requests\UpdateJadwalKuliahRequest;
use App\JadwalKuliah;
use App\MataKuliah;
use App\TimeInterval;
use Symfony\Component\HttpFoundation\Response;

class JadwalKuliahController extends Controller
{
    public function index()
    {

        $jadwalKuliah = JadwalKuliah::all();

        return view('admin.jadwalKuliah.index', compact('jadwalKuliah'));
    }

    public function create()
    {
        $mataKuliah = MataKuliah::all()->pluck('nama', 'id')->prepend(trans('global.pleaseSelect'), '');

        $hari =  JadwalKuliah::HARI;

        $startTime = TimeInterval::all()->pluck('start_time', 'id')->prepend(trans('global.pleaseSelect'), '');
        
        $endTime = TimeInterval::all()->pluck('end_time', 'id')->prepend(trans('global.pleaseSelect'), '');

        return view('admin.jadwalKuliah.create', compact('mataKuliah', 'hari', 'startTime', 'endTime'));
    }

    public function store(StoreJadwalKuliahRequest $request)
    {
        $jadwalKuliah = JadwalKuliah::create($request->all());

        return redirect()->route('admin.jadwal-kuliah.index');
    }

    public function edit(JadwalKuliah $jadwalKuliah)
    {
        $mataKuliah = MataKuliah::all()->pluck('nama', 'id')->prepend(trans('global.pleaseSelect'), '');

        $hari =  JadwalKuliah::HARI;

        $startTime = TimeInterval::all()->pluck('start_time', 'id')->prepend(trans('global.pleaseSelect'), '');
        
        $endTime = TimeInterval::all()->pluck('end_time', 'id')->prepend(trans('global.pleaseSelect'), '');

        $jadwalKuliah->load('mataKuliah');

        return view('admin.jadwalKuliah.edit', compact('mataKuliah', 'hari', 'startTime', 'endTime', 'jadwalKuliah'));
    }

    public function update(UpdateJadwalKuliahRequest $request, JadwalKuliah $jadwalKuliah)
    {
        $jadwalKuliah->update($request->all());

        return redirect()->route('admin.jadwal-kuliah.index');
    }

    public function show(JadwalKuliah $jadwalKuliah)
    {
        $jadwalKuliah->load('mataKuliah');

        return view('admin.jadwalKuliah.show', compact('jadwalKuliah'));
    }

    public function destroy(JadwalKuliah $jadwalKuliah)
    {
        $jadwalKuliah->delete();

        return back();
    }

    public function massDestroy(MassDestroyMataKuliahRequest $request)
    {
        JadwalKuliah::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

resources/views/admin/jadwalKuliah/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('cruds.jadwalKuliah.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.jadwal-kuliah.store") }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label class="required" for="mata_kuliah_id">{{ trans('cruds.jadwalKuliah.fields.mata_kuliah') }}</label>
                <select class="form-control select2 {{ $errors->has('mataKuliah') ? 'is-invalid' : '' }}" name="mata_kuliah_id" id="mata_kuliah_id" required>
                    @foreach($mataKuliah as $id => $mataKuliah)
                        <option value="{{ $id }}" {{ old('mata_kuliah_id') == $mataKuliah ? 'selected' : '' }}>{{ $mataKuliah }}</option>
                    @endforeach
                </select>
                @if($errors->has('mataKuliah'))
                    <div class="invalid-feedback">
                        {{ $errors->first('mataKuliah') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.jadwalKuliah.fields.mata_kuliah_helper') }}</span>
            </div>
            
            <div class="form-group">
                <label class="required" for="kelas">{{ trans('cruds.jadwalKuliah.fields.kelas') }}</label>
                <input class="form-control {{ $errors->has('kelas') ? 'is-invalid' : '' }}" type="text" name="kelas" id="kelas" value="{{ old('kelas', '') }}" required>
                @if($errors->has('kelas'))
                    <div class="invalid-feedback">
                        {{ $errors->first('kelas') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.mataKuliah.fields.nama_helper') }}</span>
            </div>

            <div class="form-group">
                <label class="required" for="hari">{{ trans('cruds.jadwalKuliah.fields.hari') }}</label>
                <select class="form-control select2 {{ $errors->has('hari') ? 'is-invalid' : '' }}" name="hari" id="hari" required>
                    @foreach($hari as $id => $hari)
                        <option value="{{ $hari }}" {{ old('hari') == $hari ? 'selected' : '' }}>{{ $hari }}</option>
                    @endforeach
                </select>
                @if($errors->has('hari'))
                    <div class="invalid-feedback">
                        {{ $errors->first('hari') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.jadwalKuliah.fields.hari_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="start_time">{{ trans('cruds.jadwalKuliah.fields.start_time') }}</label>
                <select class="form-control select2 {{ $errors->has('startTime') ? 'is-invalid' : '' }}" name="start_time" id="start_time" required>
                    @foreach($startTime as $id => $time)
                        <option value="{{ $time }}" {{ old('start_time') == $time ? 'selected' : '' }}>{{ $time }}</option>
                    @endforeach
                </select>
                @if($errors->has('start_time'))
                    <div class="invalid-feedback">
                        {{ $errors->first('start_time') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.jadwalKuliah.fields.end_time_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="end_time">{{ trans('cruds.jadwalKuliah.fields.end_time') }}</label>
                <select class="form-control select2 {{ $errors->has('endTime') ? 'is-invalid' : '' }}" name="end_time" id="end_time" required>
                    @foreach($endTime as $id => $time)
                        <option value="{{ $time }}" {{ old('end_time') == $time ? 'selected' : '' }}>{{ $time }}</option>
                    @endforeach
                </select>
                @if($errors->has('end_time'))
                    <div class="invalid-feedback">
                        {{ $errors->first('end_time') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.jadwalKuliah.fields.end_time_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/jadwalKuliah/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('cruds.jadwalKuliah.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.jadwal-kuliah.update", [$jadwalKuliah->id]) }}" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <div class="form-group">
                <label class="required" for="mata_kuliah_id">{{ trans('cruds.jadwalKuliah.fields.mata_kuliah') }}</label>
                <select class="form-control select2 {{ $errors->has('mataKuliah') ? 'is-invalid' : '' }}" name="mata_kuliah_id" id="mata_kuliah_id" required>
                    @foreach($mataKuliah as $id => $mataKuliah)
                        <option value="{{ $id }}" {{ ($jadwalKuliah->mataKuliah ? $jadwalKuliah->mataKuliah->nama : old('mata_kuliah_id')) == $mataKuliah ? 'selected' : '' }}>{{ $mataKuliah }}</option>
                    @endforeach
                </select>
                @if($errors->has('mataKuliah'))
                    <div class="invalid-feedback">
                        {{ $errors->first('mataKuliah') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.jadwalKuliah.fields.mata_kuliah_helper') }}</span>
            </div>
            
            <div class="form-group">
                <label class="required" for="kelas">{{ trans('cruds.jadwalKuliah.fields.kelas') }}</label>
                <input class="form-control {{ $errors->has('kelas') ? 'is-invalid' : '' }}" type="text" name="kelas" id="kelas" value="{{ old('kelas', $jadwalKuliah->kelas) }}" required>
                @if($errors->has('kelas'))
                    <div class="invalid-feedback">
                        {{ $errors->first('kelas') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.mataKuliah.fields.nama_helper') }}</span>
            </div>

            <div class="form-group">
                <label class="required" for="hari">{{ trans('cruds.jadwalKuliah.fields.hari') }}</label>
                <select class="form-control select2 {{ $errors->has('hari') ? 'is-invalid' : '' }}" name="hari" id="hari" required>
                    @foreach($hari as $id => $hari)
                        <option value="{{ $hari }}" {{ ($jadwalKuliah->hari ? $jadwalKuliah->hari : old('hari')) == $hari ? 'selected' : '' }}>{{ $hari }}</option>
                    @endforeach
                </select>
                @if($errors->has('hari'))
                    <div class="invalid-feedback">
                        {{ $errors->first('hari') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.jadwalKuliah.fields.hari_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="start_time">{{ trans('cruds.jadwalKuliah.fields.start_time') }}</label>
                <select class="form-control select2 {{ $errors->has('startTime') ? 'is-invalid' : '' }}" name="start_time" id="start_time" required>
                    @foreach($startTime as $id => $time)
                        <option value="{{ $time }}" {{ ($jadwalKuliah->start_time ? $jadwalKuliah->start_time : old('start_time')) == $time ? 'selected' : '' }}>{{ $time }}</option>
                    @endforeach
                </select>
                @if($errors->has('start_time'))
                    <div class="invalid-feedback">
                        {{ $errors->first('start_time') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.jadwalKuliah.fields.end_time_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="end_time">{{ trans('cruds.jadwalKuliah.fields.end_time') }}</label>
                <select class="form-control select2 {{ $errors->has('endTime') ? 'is-invalid' : '' }}" name="end_time" id="end_time" required>
                    @foreach($endTime as $id => $time)
                        <option value="{{ $time }}" {{ ($jadwalKuliah->end_time ? $jadwalKuliah->end_time : old('end_time')) == $time ? 'selected' : '' }}>{{ $time }}</option>
                    @endforeach
                </select>
                @if($errors->has('end_time'))
                    <div class="invalid-feedback">
                        {{ $errors->first('end_time') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.jadwalKuliah.fields.end_time_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/jadwalKuliah/index.blade.php
@extends('layouts.admin')
@section('content')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route("admin.jadwal-kuliah.create") }}">
                {{ trans('global.add') }} {{ trans('cruds.jadwalKuliah.title_singular') }}
            </a>
        </div>
    </div>
<div class="card">
    <div class="card-header">
        {{ trans('cruds.jadwalKuliah.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable datatable-Lesson">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.jadwalKuliah.fields.id') }}
                        </th>
                        <th>
                            {{ trans('cruds.jadwalKuliah.fields.mata_kuliah') }}
                        </th>
                        <th>
                            {{ trans('cruds.jadwalKuliah.fields.kelas') }}
                        </th>
                        <th>
                            {{ trans('cruds.jadwalKuliah.fields.hari') }}
                        </th>
                        <th>
                            {{ trans('cruds.jadwalKuliah.fields.start_time') }}
                        </th>
                        <th>
                            {{ trans('cruds.jadwalKuliah.fields.end_time') }}
                        </th>
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($jadwalKuliah as $key => $jadwalKuliah)
                        <tr data-entry-id="{{ $jadwalKuliah->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $jadwalKuliah->id ?? '' }}
                            </td>
                            <td>
                                {{ $jadwalKuliah->mataKuliah->nama ?? '' }}
                            </td>
                            <td>
                                {{ $jadwalKuliah->kelas ?? '' }}
                            </td>
                            <td>
                                {{ $jadwalKuliah->hari ?? '' }}
                            </td>
                            <td>
                                {{ $jadwalKuliah->start_time ?? '' }}
                            </td>
                            <td>
                                {{ $jadwalKuliah->end_time ?? '' }}
                            </td>
                            <td>
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.jadwal-kuliah.show', $jadwalKuliah->id) }}">
                                        {{ trans('global.view') }}
                                    </a>

                                    <a class="btn btn-xs btn-info" href="{{ route('admin.jadwal-kuliah.edit', $jadwalKuliah->id) }}">
                                        {{ trans('global.edit') }}
                                    </a>

                                    <form action="{{ route('admin.jadwal-kuliah.destroy', $jadwalKuliah->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>

                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>



@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.jadwal-kuliah.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)

  $.extend(true, $.fn.dataTable.defaults, {
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  $('.datatable-Lesson:not(.ajaxTable)').DataTable({ buttons: dtButtons })
    $('a[data-toggle="tab"]').on('shown.bs.tab', function(e){
        $($.fn.dataTable.tables(true)).DataTable()
            .columns.adjust();
    });
})

</script>
@endsection

resources/views/admin/jadwalKuliah/show.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('cruds.jadwalKuliah.title') }}
    </div>

    <div class="card-body">
        <div class="form-group">
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.jadwal-kuliah.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <th>
                            {{ trans('cruds.jadwalKuliah.fields.id') }}
                        </th>
                        <td>
                            {{ $jadwalKuliah->id }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.jadwalKuliah.fields.mata_kuliah') }}
                        </th>
                        <td>
                            {{ $jadwalKuliah->mataKuliah->nama ?? '' }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.jadwalKuliah.fields.kelas') }}
                        </th>
                        <td>
                            {{ $jadwalKuliah->kelas ?? '' }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.jadwalKuliah.fields.hari') }}
                        </th>
                        <td>
                            {{ $jadwalKuliah->hari }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.jadwalKuliah.fields.start_time') }}
                        </th>
                        <td>
                            {{ $jadwalKuliah->start_time }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.jadwalKuliah.fields.end_time') }}
                        </th>
                        <td>
                            {{ $jadwalKuliah->end_time }}
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.jadwal-kuliah.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
        </div>
    </div>
</div>



@endsection