routes/web.php
<?php

Route::redirect('/', '/register');
Route::get('/home', function () {
    $routeName = 'admin.home'; 
    if (session('status')) {
        return redirect()->route($routeName)->with('status', session('status'));
    }

    return redirect()->route($routeName);
});

Auth::routes(['register' => true]);
// Admin

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Jadwal Kuliah
    Route::delete('jadwal-kuliah/destroy', 'JadwalKuliahController@massDestroy')->name('jadwal-kuliah.massDestroy');
    Route::resource('jadwal-kuliah', 'JadwalKuliahController');

    // Mata Kuliah
    Route::delete('mata-kuliah/destroy', 'MataKuliahController@massDestroy')->name('mata-kuliah.massDestroy');
    Route::resource('mata-kuliah', 'MataKuliahController');

    // Time Interval
    Route::delete('time-interval/destroy', 'TimeIntervalControllerr@massDestroy')->name('time-interval.massDestroy');
    Route::resource('time-interval', 'TimeIntervalController');
    
    Route::get('calendar', 'CalendarController@index')->name('calendar.index');
});

app/TimeInterval.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class TimeInterval extends Model
{
    use SoftDeletes;

    public $table = 'time_interval';

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'start_time',
        'end_time',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    public function getDifferenceAttribute()
    {
        return Carbon::parse($this->end_time)->diffInMinutes($this->start_time);
    }

    public function getStartTimeAttribute($value)
    {
        return $value ? Carbon::createFromFormat('H:i:s', $value)->format(config('panel.lesson_time_format')) : null;
    }

    public function setStartTimeAttribute($value)
    {
        $this->attributes['start_time'] = $value ? Carbon::createFromFormat(config('panel.lesson_time_format'),
            $value)->format('H:i:s') : null;
    }

    public function getEndTimeAttribute($value)
    {
        return $value ? Carbon::createFromFormat('H:i:s', $value)->format(config('panel.lesson_time_format')) : null;
    }

    public function setEndTimeAttribute($value)
    {
        $this->attributes['end_time'] = $value ? Carbon::createFromFormat(config('panel.lesson_time_format'),
            $value)->format('H:i:s') : null;
    }
}

app/Http/Controllers/Admin/TimeIntervalController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroySchoolClassRequest;
use App\Http\Requests\MassDestroyTimeIntervalRequest;
use App\Http\Requests\StoreSchoolClassRequest;
use App\Http\Requests\StoreTimeIntervalRequest;
use App\Http\Requests\UpdateSchoolClassRequest;
use App\Http\Requests\UpdateTimeIntervalRequest;
use App\TimeInterval;
use Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class TimeIntervalController extends Controller
{
    public function index()
    {
        $timeInterval = TimeInterval::all();

        return view('admin.timeInterval.index', compact('timeInterval'));
    }

    public function create()
    {
        return view('admin.timeInterval.create');
    }

    public function store(StoreTimeIntervalRequest $request)
    {
        $timeInterval = TimeInterval::create($request->all());

        return redirect()->route('admin.time-interval.index');
    }

    public function edit(TimeInterval $timeInterval)
    {
        return view('admin.timeInterval.edit', compact('timeInterval'));
    }

    public function update(UpdateTimeIntervalRequest $request, TimeInterval $timeInterval)
    {
        $timeInterval->update($request->all());

        return redirect()->route('admin.time-interval.index');
    }

    public function show(TimeInterval $timeInterval)
    {
        return view('admin.timeInterval.show', compact('timeInterval'));
    }

    public function destroy(TimeInterval $timeInterval)
    {
        $timeInterval->delete();

        return back();
    }

    public function massDestroy(MassDestroyTimeIntervalRequest $request)
    {
        TimeInterval::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

resources/views/admin/timeInterval/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('cruds.timeInterval.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.time-interval.store") }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label class="required" for="start_time">{{ trans('cruds.timeInterval.fields.start_time') }}</label>
                <input class="form-control {{ $errors->has('start_time') ? 'is-invalid' : '' }}" type="time" name="start_time" id="start_time" value="{{ old('start_time') }}" required>
                @if($errors->has('start_time'))
                    <div class="invalid-feedback">
                        {{ $errors->first('start_time') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.timeInterval.fields.start_time_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="end_time">{{ trans('cruds.timeInterval.fields.end_time') }}</label>
                <input class="form-control {{ $errors->has('end_time') ? 'is-invalid' : '' }}" type="time" name="end_time" id="end_time" value="{{ old('end_time') }}" required>
                @if($errors->has('name'))
                    <div class="invalid-feedback">
                        {{ $errors->first('end_time') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.timeInterval.fields.end_time_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/timeInterval/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('cruds.timeInterval.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.time-interval.update", [$timeInterval->id]) }}" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <div class="form-group">
                <label class="required" for="start_time">{{ trans('cruds.timeInterval.fields.start_time') }}</label>
                <input class="form-control {{ $errors->has('start_time') ? 'is-invalid' : '' }}" type="time" name="start_time" id="start_time" value="{{ old('start_time', $timeInterval->start_time) }}" required>
                @if($errors->has('start_time'))
                    <div class="invalid-feedback">
                        {{ $errors->first('start_time') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.timeInterval.fields.start_time_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="end_time">{{ trans('cruds.timeInterval.fields.end_time') }}</label>
                <input class="form-control {{ $errors->has('end_time') ? 'is-invalid' : '' }}" type="time" name="end_time" id="end_time" value="{{ old('end_time', $timeInterval->end_time) }}" required>
                @if($errors->has('name'))
                    <div class="invalid-feedback">
                        {{ $errors->first('end_time') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.timeInterval.fields.end_time_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/timeInterval/index.blade.php
@extends('layouts.admin')
@section('content')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route("admin.time-interval.create") }}">
                {{ trans('global.add') }} {{ trans('cruds.timeInterval.title_singular') }}
            </a>
        </div>
    </div>
<div class="card">
    <div class="card-header">
        {{ trans('cruds.timeInterval.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable datatable-timeInterval">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.timeInterval.fields.id') }}
                        </th>
                        <th>
                            {{ trans('cruds.timeInterval.fields.start_time') }}
                        </th>
                        <th>
                            {{ trans('cruds.timeInterval.fields.end_time') }}
                        </th>
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($timeInterval as $key => $timeInterval)
                        <tr data-entry-id="{{ $timeInterval->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $timeInterval->id ?? '' }}
                            </td>
                            <td>
                                {{ $timeInterval->start_time ?? '' }}
                            </td>
                            <td>
                                {{ $timeInterval->end_time ?? '' }}
                            </td>
                            <td>
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.time-interval.show', $timeInterval->id) }}">
                                        {{ trans('global.view') }}
                                    </a>

                                    <a class="btn btn-xs btn-info" href="{{ route('admin.time-interval.edit', $timeInterval->id) }}">
                                        {{ trans('global.edit') }}
                                    </a>

                                    <form action="{{ route('admin.time-interval.destroy', $timeInterval->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>

                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>



@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('time_interval_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.school-classes.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  $('.datatable-timeInterval:not(.ajaxTable)').DataTable({ buttons: dtButtons })
    $('a[data-toggle="tab"]').on('shown.bs.tab', function(e){
        $($.fn.dataTable.tables(true)).DataTable()
            .columns.adjust();
    });
})

</script>
@endsection

resources/views/admin/timeInterval/show.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('cruds.timeInterval.title') }}
    </div>

    <div class="card-body">
        <div class="form-group">
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.time-interval.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <th>
                            {{ trans('cruds.timeInterval.fields.id') }}
                        </th>
                        <td>
                            {{ $timeInterval->id }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.timeInterval.fields.start_time') }}
                        </th>
                        <td>
                            {{ $timeInterval->start_time }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.timeInterval.fields.end_time') }}
                        </th>
                        <td>
                            {{ $timeInterval->end_time }}
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.time-interval.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
        </div>
    </div>

</div>

@endsection