routes/web.php
<?php

Route::redirect('/', '/register');
Route::get('/home', function () {
    $routeName = 'admin.home'; 
    if (session('status')) {
        return redirect()->route($routeName)->with('status', session('status'));
    }

    return redirect()->route($routeName);
});

Auth::routes(['register' => true]);
// Admin

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Jadwal Kuliah
    Route::delete('jadwal-kuliah/destroy', 'JadwalKuliahController@massDestroy')->name('jadwal-kuliah.massDestroy');
    Route::resource('jadwal-kuliah', 'JadwalKuliahController');

    // Mata Kuliah
    Route::delete('mata-kuliah/destroy', 'MataKuliahController@massDestroy')->name('mata-kuliah.massDestroy');
    Route::resource('mata-kuliah', 'MataKuliahController');

    // Time Interval
    Route::delete('time-interval/destroy', 'TimeIntervalControllerr@massDestroy')->name('time-interval.massDestroy');
    Route::resource('time-interval', 'TimeIntervalController');
    
    Route::get('calendar', 'CalendarController@index')->name('calendar.index');
});

app/MataKuliah.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class MataKuliah extends Model
{
    use SoftDeletes;

    public $table = 'mata_kuliah';

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'nama',
        'kode',
        'sks',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    public function mataKuliahJadwal()
    {
        return $this->hasMany(JadwalKuliah::class, 'mata_kuliah_id', 'id');
    }
}

app/Http/Controllers/Admin/MataKuliahController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroyMataKuliahRequest;
use App\Http\Requests\StoreMataKuliahRequest;
use App\Http\Requests\UpdateMataKuliahRequest;
use App\MataKuliah;
use Symfony\Component\HttpFoundation\Response;

class MataKuliahController extends Controller
{
    public function index()
    {
        $mataKuliah = MataKuliah::all();

        return view('admin.mataKuliah.index', compact('mataKuliah'));
    }

    public function create()
    {
        return view('admin.mataKuliah.create');
    }

    public function store(StoreMataKuliahRequest $request)
    {
        $mataKuliah = MataKuliah::create($request->all());

        return redirect()->route('admin.mata-kuliah.index');
    }

    public function edit(MataKuliah $mataKuliah)
    {
        return view('admin.mataKuliah.edit', compact('mataKuliah'));
    }

    public function update(UpdateMataKuliahRequest $request, MataKuliah $mataKuliah)
    {
        $mataKuliah->update($request->all());

        return redirect()->route('admin.mata-kuliah.index');
    }

    public function show(MataKuliah $mataKuliah)
    {
        return view('admin.mataKuliah.show', compact('mataKuliah'));
    }

    public function destroy(MataKuliah $mataKuliah)
    {
        $mataKuliah->delete();

        return back();
    }

    public function massDestroy(MassDestroyMataKuliahRequest $request)
    {
        MataKuliah::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

resources/views/admin/mataKuliah/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('cruds.mataKuliah.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.mata-kuliah.store") }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label class="required" for="nama">{{ trans('cruds.mataKuliah.fields.nama') }}</label>
                <input class="form-control {{ $errors->has('nama') ? 'is-invalid' : '' }}" type="text" name="nama" id="nama" value="{{ old('nama', '') }}" required>
                @if($errors->has('nama'))
                    <div class="invalid-feedback">
                        {{ $errors->first('nama') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.mataKuliah.fields.nama_helper') }}</span>
            </div>

            <div class="form-group">
                <label class="required" for="kode">{{ trans('cruds.mataKuliah.fields.kode') }}</label>
                <input class="form-control {{ $errors->has('kode') ? 'is-invalid' : '' }}" type="text" name="kode" id="kode" value="{{ old('kode', '') }}" required>
                @if($errors->has('kode'))
                    <div class="invalid-feedback">
                        {{ $errors->first('kode') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.mataKuliah.fields.kode_helper') }}</span>
            </div>

            <div class="form-group">
                <label class="required" for="sks">{{ trans('cruds.mataKuliah.fields.sks') }}</label>
                <input class="form-control {{ $errors->has('sks') ? 'is-invalid' : '' }}" type="text" name="sks" id="sks" value="{{ old('sks', '') }}" required>
                @if($errors->has('sks'))
                    <div class="invalid-feedback">
                        {{ $errors->first('sks') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.mataKuliah.fields.sks_helper') }}</span>
            </div>

            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/mataKuliah/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('cruds.mataKuliah.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.mata-kuliah.update", [$mataKuliah->id]) }}" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <div class="form-group">
                <label class="required" for="nama">{{ trans('cruds.mataKuliah.fields.nama') }}</label>
                <input class="form-control {{ $errors->has('nama') ? 'is-invalid' : '' }}" type="text" name="nama" id="nama" value="{{ old('nama', $mataKuliah->nama) }}" required>
                @if($errors->has('nama'))
                    <div class="invalid-feedback">
                        {{ $errors->first('nama') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.mataKuliah.fields.nama_helper') }}</span>
            </div>

            <div class="form-group">
                <label class="required" for="kode">{{ trans('cruds.mataKuliah.fields.kode') }}</label>
                <input class="form-control {{ $errors->has('kode') ? 'is-invalid' : '' }}" type="text" name="kode" id="kode" value="{{ old('kode', $mataKuliah->kode) }}" required>
                @if($errors->has('kode'))
                    <div class="invalid-feedback">
                        {{ $errors->first('kode') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.mataKuliah.fields.kode_helper') }}</span>
            </div>

            <div class="form-group">
                <label class="required" for="sks">{{ trans('cruds.mataKuliah.fields.sks') }}</label>
                <input class="form-control {{ $errors->has('sks') ? 'is-invalid' : '' }}" type="text" name="sks" id="sks" value="{{ old('sks', $mataKuliah->sks) }}" required>
                @if($errors->has('sks'))
                    <div class="invalid-feedback">
                        {{ $errors->first('sks') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.mataKuliah.fields.sks_helper') }}</span>
            </div>

            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/mataKuliah/index.blade.php
@extends('layouts.admin')
@section('content')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route("admin.mata-kuliah.create") }}">
                {{ trans('global.add') }} {{ trans('cruds.mataKuliah.title_singular') }}
            </a>
        </div>
    </div>
<div class="card">
    <div class="card-header">
        {{ trans('cruds.mataKuliah.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable datatable-SchoolClass">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.mataKuliah.fields.id') }}
                        </th>
                        <th>
                            {{ trans('cruds.mataKuliah.fields.nama') }}
                        </th>
                        <th>
                            {{ trans('cruds.mataKuliah.fields.kode') }}
                        </th>
                        <th>
                            {{ trans('cruds.mataKuliah.fields.sks') }}
                        </th>
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($mataKuliah as $key => $mataKuliah)
                        <tr data-entry-id="{{ $mataKuliah->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $mataKuliah->id ?? '' }}
                            </td>
                            <td>
                                {{ $mataKuliah->nama ?? '' }}
                            </td>
                            <td>
                                {{ $mataKuliah->kode ?? '' }}
                            </td>
                            <td>
                                {{ $mataKuliah->sks ?? '' }}
                            </td>
                            <td>
                                <a class="btn btn-xs btn-primary" href="{{ route('admin.mata-kuliah.show', $mataKuliah->id) }}">
                                    {{ trans('global.view') }}
                                </a>
                                
                                <a class="btn btn-xs btn-info" href="{{ route('admin.mata-kuliah.edit', $mataKuliah->id) }}">
                                    {{ trans('global.edit') }}
                                </a>

                                <form action="{{ route('admin.mata-kuliah.destroy', $mataKuliah->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                    <input type="hidden" name="_method" value="DELETE">
                                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                    <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                </form>

                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>



@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.mata-kuliah.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)

  $.extend(true, $.fn.dataTable.defaults, {
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  $('.datatable-SchoolClass:not(.ajaxTable)').DataTable({ buttons: dtButtons })
    $('a[data-toggle="tab"]').on('shown.bs.tab', function(e){
        $($.fn.dataTable.tables(true)).DataTable()
            .columns.adjust();
    });
})

</script>
@endsection

resources/views/admin/mataKuliah/show.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('cruds.mataKuliah.title') }}
    </div>

    <div class="card-body">
        <div class="form-group">
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.mata-kuliah.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <th>
                            {{ trans('cruds.mataKuliah.fields.id') }}
                        </th>
                        <td>
                            {{ $mataKuliah->id }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.mataKuliah.fields.nama') }}
                        </th>
                        <td>
                            {{ $mataKuliah->nama }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.mataKuliah.fields.kode') }}
                        </th>
                        <td>
                            {{ $mataKuliah->kode }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.mataKuliah.fields.sks') }}
                        </th>
                        <td>
                            {{ $mataKuliah->sks }}
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.mata-kuliah.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
        </div>
    </div>
</div>

@endsection